# Generated by Django 4.1.4 on 2023-02-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_cpf_alter_usuario_data_nascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
