# Generated by Django 4.1.4 on 2023-01-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
